### ISSUE TITLE
Newspaper image is not a mockup

### ISSUE THREAD

**Issue by lucaswillering** [EngineersNeedArt/SystemSix#2]
Not an issue, but I couldn't find another way to leave a message. In your blog post about SystemSix you include a screenshot of the New York Times on a big e-ink screen, with the caption: "An expensive e-ink newspaper project, this one possibly a mock-up?"

I believe it's not a mockup, you can find more details about the project here: https://alexanderklopping.medium.com/an-updated-daily-front-page-of-the-new-york-times-as-artwork-on-your-wall-3b28c3261478

**Comment by EngineersNeedArt** [comment]
Hey, that's cool. I had seen something like it but did not know if the image I pulled of the internet was legit.'

I'll update. Thank you.
