### ISSUE TITLE
Use non-Retina resolution to avoid needing to downsample screenshots

### ISSUE THREAD

**Issue by ryandesign** [EngineersNeedArt/SystemSix#3]
Fantastic project! Thanks for sharing. Loved reading your write-up.

You spent some time talking about using [GraphicsMagick](http://www.graphicsmagick.org/) to downsample Retina-resolution (pixel-doubled) [Mini vMac](https://www.gryphel.com/c/minivmac/) screenshots. (Its cousin [ImageMagick](https://imagemagick.org) is another choice.) Wanted to let you know you can avoid the need for that step by setting your screen to a non-Retina (non-HiDPI) resolution prior to making the screenshots using a utility such as [RDM](https://github.com/avibrazil/RDM). Or connect an external non-Retina display to your computer and drag the Mini vMac window onto that display before screenshotting it.

**Comment by EngineersNeedArt** [comment]
Thanks for the suggestions. I did see ImageMagick as well as GraphicsMagick. I am not sure what the difference it, why I went with GraphicsMagick. Still, having dipped my toe in using it, I suspect it will come in handy in the future for other tasks (where using a non-Retina display with Mini vMac would not be the solution, ha ha).

Always Be Learning.
(Always Be Iterating is _actually_ my motto.)
